# Generated by Django 6.0 on 2026-02-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nessage',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(null=True),
        ),
    ]
