# Generated by Django 6.0 on 2026-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(null=True)),
                ('phone', models.CharField(null=True)),
                ('nessage', models.CharField(null=True)),
            ],
        ),
    ]
